name: Deploy Using Shared Workflow

on:
  pull_request:
    types: [opened, reopened, synchronize]  # Triggers on PR raised or reopened
    branches:
      - main  # Only trigger for PRs targeting main
  push:
    branches:
      - main  # Triggers on push to main

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-dev:
    uses: seannguyn/actions/.github/workflows/serverless.yaml@main
    if: github.event_name == 'pull_request'
    environment: dev  # Static environment name
    with:
      docker_repo: ${{ vars.DOCKER_REPO }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GH_PAT: ${{ secrets.GH_PAT }}
  deploy-prod:
    uses: seannguyn/actions/.github/workflows/serverless.yaml@main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: prod  # Static environment name
    with:
      docker_repo: ${{ vars.DOCKER_REPO }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GH_PAT: ${{ secrets.GH_PAT }}
