name: Deploy Using Shared Workflow

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    uses: seannguyn/actions/.github/workflows/serverless.yaml@main
    with:
      docker_repo: ${{ vars.DOCKER_REPO }} 
      environment: ${{ github.event_name == 'pull_request' && 'dev' || 'prod' }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GH_PAT: ${{ secrets.GH_PAT }}
